cv_folds:              5
early_stopping_rounds: 50
N_iterations:          3000
N_samples:             200
upper_planet_radius:   2.0
lower_planet_radius:   1.0

features: ['C', 'O', 'Mg', 'Si', 'Ti', 'Fe']

dropnans: True
